-- Create keep_alive table and policy for Supabase Keep Alive workflow
CREATE TABLE IF NOT EXISTS keep_alive (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  last_ping timestamptz DEFAULT now()
);

INSERT INTO keep_alive DEFAULT VALUES;

ALTER TABLE keep_alive ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow keep alive read"
ON keep_alive
FOR SELECT
TO anon
USING (true);
