-- Update keep_alive table and policies to allow updates securely
CREATE TABLE IF NOT EXISTS keep_alive (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  last_ping timestamptz DEFAULT now()
);

INSERT INTO keep_alive (id, last_ping)
VALUES (1, now())
ON CONFLICT (id)
DO UPDATE SET last_ping = now();

ALTER TABLE keep_alive ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow keep alive read" ON keep_alive;
DROP POLICY IF EXISTS "Allow keep alive update" ON keep_alive;

CREATE POLICY "Allow keep alive read"
ON keep_alive
FOR SELECT
TO anon
USING (id = 1);

CREATE POLICY "Allow keep alive update"
ON keep_alive
FOR UPDATE
TO anon
USING (id = 1)
WITH CHECK (id = 1);
